# Generated by Django 5.1 on 2024-08-11 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0002_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='stack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='vocab.stack'),
            preserve_default=False,
        ),
    ]
