# Generated by Django 5.1 on 2024-08-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0005_alter_card_quiz_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='last_quiz_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
