# Generated by Django 5.1 on 2024-08-26 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0006_stack_last_quiz_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StackTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.stack')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.tag')),
            ],
            options={
                'unique_together': {('stack', 'tag')},
            },
        ),
    ]
