# Generated by Django 5.1 on 2024-08-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0007_tag_stacktag'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='stacks', to='vocab.tag'),
        ),
    ]
