# Generated by Django 5.1 on 2024-08-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0010_tag_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='back_desc',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='front_desc',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
